<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="TUnit" />
    <ProjectReference Include="../CheckAndThrow.Analyzers/CheckAndThrow.Analyzers.csproj" />
    <ProjectReference Include="../CheckAndThrow/CheckAndThrow.csproj" />
  </ItemGroup>
</Project>
